# Copyright 2023 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  modules-download-mode: readonly
  deadline: 20m
  skip-files:
    - zz_generated.*.go

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - staticcheck
    - tenv
    - unconvert
    - unused
    - wastedassign
    - whitespace
  disable-all: true

linters-settings:
  depguard:
    include-go-root: true
    packages:
      - io/ioutil # https://go.dev/doc/go1.16#ioutil
      - github.com/ghodss/yaml # use sigs.k8s.io/yaml instead
      - sigs.k8s.io/controller-runtime # we never want to pull in the entire kitchen sink
      - github.com/kubermatic/machine-controller # prevent import loops across modules
      - k8c.io/operating-system-manager # prevent import loops across modules
      - k8c.io/dashboard # prevent import loops across modules

  importas:
    no-unaliased: true
    alias:
      - pkg: k8c.io/api/v3/pkg/apis/kubermatic/v1
        alias: kubermaticv1
      - pkg: k8c.io/api/v3/pkg/apis/ee.kubermatic/v1
        alias: kubermaticeev1
      - pkg: k8c.io/api/v3/pkg/apis/apps.kubermatic/v1
        alias: kubermaticappsv1
      - pkg: k8c.io/api/v3/pkg/apis/ee.apps.kubermatic/v1
        alias: kubermaticappseev1

      - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      - pkg: github.com/Masterminds/semver/v3
        alias: semverlib
