//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright  The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	kubermaticv1 "k8c.io/api/v3/pkg/apis/kubermatic/v1"
	"k8c.io/api/v3/pkg/semver"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AKSPreset) DeepCopyInto(out *AKSPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AKSPreset.
func (in *AKSPreset) DeepCopy() *AKSPreset {
	if in == nil {
		return nil
	}
	out := new(AKSPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPreset) DeepCopyInto(out *AWSPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPreset.
func (in *AWSPreset) DeepCopy() *AWSPreset {
	if in == nil {
		return nil
	}
	out := new(AWSPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Addon) DeepCopyInto(out *Addon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Addon.DeepCopyInto(&out.Addon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Addon.
func (in *Addon) DeepCopy() *Addon {
	if in == nil {
		return nil
	}
	out := new(Addon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Addon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonConfig) DeepCopyInto(out *AddonConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.AddonConfig.DeepCopyInto(&out.AddonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonConfig.
func (in *AddonConfig) DeepCopy() *AddonConfig {
	if in == nil {
		return nil
	}
	out := new(AddonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AddonConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonConfigList) DeepCopyInto(out *AddonConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AddonConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonConfigList.
func (in *AddonConfigList) DeepCopy() *AddonConfigList {
	if in == nil {
		return nil
	}
	out := new(AddonConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AddonConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonList) DeepCopyInto(out *AddonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Addon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonList.
func (in *AddonList) DeepCopy() *AddonList {
	if in == nil {
		return nil
	}
	out := new(AddonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AddonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionPlugin) DeepCopyInto(out *AdmissionPlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.AdmissionPlugin.DeepCopyInto(&out.AdmissionPlugin)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionPlugin.
func (in *AdmissionPlugin) DeepCopy() *AdmissionPlugin {
	if in == nil {
		return nil
	}
	out := new(AdmissionPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdmissionPlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionPluginList) DeepCopyInto(out *AdmissionPluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdmissionPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionPluginList.
func (in *AdmissionPluginList) DeepCopy() *AdmissionPluginList {
	if in == nil {
		return nil
	}
	out := new(AdmissionPluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdmissionPluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alertmanager) DeepCopyInto(out *Alertmanager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Alertmanager.DeepCopyInto(&out.Alertmanager)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alertmanager.
func (in *Alertmanager) DeepCopy() *Alertmanager {
	if in == nil {
		return nil
	}
	out := new(Alertmanager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Alertmanager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertmanagerList) DeepCopyInto(out *AlertmanagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Alertmanager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertmanagerList.
func (in *AlertmanagerList) DeepCopy() *AlertmanagerList {
	if in == nil {
		return nil
	}
	out := new(AlertmanagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertmanagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlibabaPreset) DeepCopyInto(out *AlibabaPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlibabaPreset.
func (in *AlibabaPreset) DeepCopy() *AlibabaPreset {
	if in == nil {
		return nil
	}
	out := new(AlibabaPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRegistry) DeepCopyInto(out *AllowedRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.AllowedRegistry.DeepCopyInto(&out.AllowedRegistry)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRegistry.
func (in *AllowedRegistry) DeepCopy() *AllowedRegistry {
	if in == nil {
		return nil
	}
	out := new(AllowedRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AllowedRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRegistryList) DeepCopyInto(out *AllowedRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AllowedRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRegistryList.
func (in *AllowedRegistryList) DeepCopy() *AllowedRegistryList {
	if in == nil {
		return nil
	}
	out := new(AllowedRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AllowedRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnexiaPreset) DeepCopyInto(out *AnexiaPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnexiaPreset.
func (in *AnexiaPreset) DeepCopy() *AnexiaPreset {
	if in == nil {
		return nil
	}
	out := new(AnexiaPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLoggingSettings) DeepCopyInto(out *AuditLoggingSettings) {
	*out = *in
	if in.SidecarSettings != nil {
		in, out := &in.SidecarSettings, &out.SidecarSettings
		*out = new(AuditSidecarSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLoggingSettings.
func (in *AuditLoggingSettings) DeepCopy() *AuditLoggingSettings {
	if in == nil {
		return nil
	}
	out := new(AuditLoggingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditSidecarConfiguration) DeepCopyInto(out *AuditSidecarConfiguration) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditSidecarConfiguration.
func (in *AuditSidecarConfiguration) DeepCopy() *AuditSidecarConfiguration {
	if in == nil {
		return nil
	}
	out := new(AuditSidecarConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditSidecarSettings) DeepCopyInto(out *AuditSidecarSettings) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(AuditSidecarConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditSidecarSettings.
func (in *AuditSidecarSettings) DeepCopy() *AuditSidecarSettings {
	if in == nil {
		return nil
	}
	out := new(AuditSidecarSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePreset) DeepCopyInto(out *AzurePreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePreset.
func (in *AzurePreset) DeepCopy() *AzurePreset {
	if in == nil {
		return nil
	}
	out := new(AzurePreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEncryptionStatus) DeepCopyInto(out *ClusterEncryptionStatus) {
	*out = *in
	if in.EncryptedResources != nil {
		in, out := &in.EncryptedResources, &out.EncryptedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEncryptionStatus.
func (in *ClusterEncryptionStatus) DeepCopy() *ClusterEncryptionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterEncryptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReference.
func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.ClusterSpec.DeepCopyInto(&out.ClusterSpec)
	if in.EnableUserSSHKeyAgent != nil {
		in, out := &in.EnableUserSSHKeyAgent, &out.EnableUserSSHKeyAgent
		*out = new(bool)
		**out = **in
	}
	if in.AuditLogging != nil {
		in, out := &in.AuditLogging, &out.AuditLogging
		*out = new(AuditLoggingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionConfiguration != nil {
		in, out := &in.EncryptionConfiguration, &out.EncryptionConfiguration
		*out = new(EncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.ClusterStatus.DeepCopyInto(&out.ClusterStatus)
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(ClusterEncryptionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceUsage != nil {
		in, out := &in.ResourceUsage, &out.ResourceUsage
		*out = new(ResourceDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTemplate) DeepCopyInto(out *ClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ClusterTemplate.DeepCopyInto(&out.ClusterTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTemplate.
func (in *ClusterTemplate) DeepCopy() *ClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTemplateInstance) DeepCopyInto(out *ClusterTemplateInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ClusterTemplateInstance.DeepCopyInto(&out.ClusterTemplateInstance)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTemplateInstance.
func (in *ClusterTemplateInstance) DeepCopy() *ClusterTemplateInstance {
	if in == nil {
		return nil
	}
	out := new(ClusterTemplateInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTemplateInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTemplateInstanceList) DeepCopyInto(out *ClusterTemplateInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTemplateInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTemplateInstanceList.
func (in *ClusterTemplateInstanceList) DeepCopy() *ClusterTemplateInstanceList {
	if in == nil {
		return nil
	}
	out := new(ClusterTemplateInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTemplateInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTemplateList) DeepCopyInto(out *ClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTemplateList.
func (in *ClusterTemplateList) DeepCopy() *ClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(ClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Constraint) DeepCopyInto(out *Constraint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ConstraintSpec.DeepCopyInto(&out.ConstraintSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Constraint.
func (in *Constraint) DeepCopy() *Constraint {
	if in == nil {
		return nil
	}
	out := new(Constraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Constraint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintList) DeepCopyInto(out *ConstraintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Constraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintList.
func (in *ConstraintList) DeepCopy() *ConstraintList {
	if in == nil {
		return nil
	}
	out := new(ConstraintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplate) DeepCopyInto(out *ConstraintTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ConstraintTemplate.DeepCopyInto(&out.ConstraintTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplate.
func (in *ConstraintTemplate) DeepCopy() *ConstraintTemplate {
	if in == nil {
		return nil
	}
	out := new(ConstraintTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplateList) DeepCopyInto(out *ConstraintTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConstraintTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplateList.
func (in *ConstraintTemplateList) DeepCopy() *ConstraintTemplateList {
	if in == nil {
		return nil
	}
	out := new(ConstraintTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardConfiguration) DeepCopyInto(out *DashboardConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.DashboardConfiguration.DeepCopyInto(&out.DashboardConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardConfiguration.
func (in *DashboardConfiguration) DeepCopy() *DashboardConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardConfigurationList) DeepCopyInto(out *DashboardConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DashboardConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardConfigurationList.
func (in *DashboardConfigurationList) DeepCopy() *DashboardConfigurationList {
	if in == nil {
		return nil
	}
	out := new(DashboardConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigitaloceanPreset) DeepCopyInto(out *DigitaloceanPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigitaloceanPreset.
func (in *DigitaloceanPreset) DeepCopy() *DigitaloceanPreset {
	if in == nil {
		return nil
	}
	out := new(DigitaloceanPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSPreset) DeepCopyInto(out *EKSPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSPreset.
func (in *EKSPreset) DeepCopy() *EKSPreset {
	if in == nil {
		return nil
	}
	out := new(EKSPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionConfiguration) DeepCopyInto(out *EncryptionConfiguration) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Secretbox != nil {
		in, out := &in.Secretbox, &out.Secretbox
		*out = new(SecretboxEncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionConfiguration.
func (in *EncryptionConfiguration) DeepCopy() *EncryptionConfiguration {
	if in == nil {
		return nil
	}
	out := new(EncryptionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdBackupConfig) DeepCopyInto(out *EtcdBackupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.EtcdBackupConfig.DeepCopyInto(&out.EtcdBackupConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdBackupConfig.
func (in *EtcdBackupConfig) DeepCopy() *EtcdBackupConfig {
	if in == nil {
		return nil
	}
	out := new(EtcdBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdBackupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdBackupConfigList) DeepCopyInto(out *EtcdBackupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EtcdBackupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdBackupConfigList.
func (in *EtcdBackupConfigList) DeepCopy() *EtcdBackupConfigList {
	if in == nil {
		return nil
	}
	out := new(EtcdBackupConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdBackupConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdRestore) DeepCopyInto(out *EtcdRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.EtcdRestore.DeepCopyInto(&out.EtcdRestore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdRestore.
func (in *EtcdRestore) DeepCopy() *EtcdRestore {
	if in == nil {
		return nil
	}
	out := new(EtcdRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdRestoreList) DeepCopyInto(out *EtcdRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EtcdRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdRestoreList.
func (in *EtcdRestoreList) DeepCopy() *EtcdRestoreList {
	if in == nil {
		return nil
	}
	out := new(EtcdRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedClusterHealth) DeepCopyInto(out *ExtendedClusterHealth) {
	*out = *in
	if in.OpenVPN != nil {
		in, out := &in.OpenVPN, &out.OpenVPN
		*out = new(HealthStatus)
		**out = **in
	}
	if in.Konnectivity != nil {
		in, out := &in.Konnectivity, &out.Konnectivity
		*out = new(HealthStatus)
		**out = **in
	}
	if in.GatekeeperController != nil {
		in, out := &in.GatekeeperController, &out.GatekeeperController
		*out = new(HealthStatus)
		**out = **in
	}
	if in.GatekeeperAudit != nil {
		in, out := &in.GatekeeperAudit, &out.GatekeeperAudit
		*out = new(HealthStatus)
		**out = **in
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(HealthStatus)
		**out = **in
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(HealthStatus)
		**out = **in
	}
	if in.AlertmanagerConfig != nil {
		in, out := &in.AlertmanagerConfig, &out.AlertmanagerConfig
		*out = new(HealthStatus)
		**out = **in
	}
	if in.MLAGateway != nil {
		in, out := &in.MLAGateway, &out.MLAGateway
		*out = new(HealthStatus)
		**out = **in
	}
	if in.OperatingSystemManager != nil {
		in, out := &in.OperatingSystemManager, &out.OperatingSystemManager
		*out = new(HealthStatus)
		**out = **in
	}
	if in.KubernetesDashboard != nil {
		in, out := &in.KubernetesDashboard, &out.KubernetesDashboard
		*out = new(HealthStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedClusterHealth.
func (in *ExtendedClusterHealth) DeepCopy() *ExtendedClusterHealth {
	if in == nil {
		return nil
	}
	out := new(ExtendedClusterHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalCluster) DeepCopyInto(out *ExternalCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ExternalCluster.DeepCopyInto(&out.ExternalCluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalCluster.
func (in *ExternalCluster) DeepCopy() *ExternalCluster {
	if in == nil {
		return nil
	}
	out := new(ExternalCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterList) DeepCopyInto(out *ExternalClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterList.
func (in *ExternalClusterList) DeepCopy() *ExternalClusterList {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterProviderVersioningConfiguration) DeepCopyInto(out *ExternalClusterProviderVersioningConfiguration) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]semver.Semver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Updates != nil {
		in, out := &in.Updates, &out.Updates
		*out = make([]semver.Semver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterProviderVersioningConfiguration.
func (in *ExternalClusterProviderVersioningConfiguration) DeepCopy() *ExternalClusterProviderVersioningConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterProviderVersioningConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakePreset) DeepCopyInto(out *FakePreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakePreset.
func (in *FakePreset) DeepCopy() *FakePreset {
	if in == nil {
		return nil
	}
	out := new(FakePreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPreset) DeepCopyInto(out *GCPPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPreset.
func (in *GCPPreset) DeepCopy() *GCPPreset {
	if in == nil {
		return nil
	}
	out := new(GCPPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEPreset) DeepCopyInto(out *GKEPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEPreset.
func (in *GKEPreset) DeepCopy() *GKEPreset {
	if in == nil {
		return nil
	}
	out := new(GKEPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfigMapKeySelector) DeepCopyInto(out *GlobalConfigMapKeySelector) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfigMapKeySelector.
func (in *GlobalConfigMapKeySelector) DeepCopy() *GlobalConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(GlobalConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalObjectKeySelector) DeepCopyInto(out *GlobalObjectKeySelector) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalObjectKeySelector.
func (in *GlobalObjectKeySelector) DeepCopy() *GlobalObjectKeySelector {
	if in == nil {
		return nil
	}
	out := new(GlobalObjectKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSecretKeySelector) DeepCopyInto(out *GlobalSecretKeySelector) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSecretKeySelector.
func (in *GlobalSecretKeySelector) DeepCopy() *GlobalSecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(GlobalSecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupProjectBinding) DeepCopyInto(out *GroupProjectBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupProjectBinding.
func (in *GroupProjectBinding) DeepCopy() *GroupProjectBinding {
	if in == nil {
		return nil
	}
	out := new(GroupProjectBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupProjectBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupProjectBindingList) DeepCopyInto(out *GroupProjectBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GroupProjectBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupProjectBindingList.
func (in *GroupProjectBindingList) DeepCopy() *GroupProjectBindingList {
	if in == nil {
		return nil
	}
	out := new(GroupProjectBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupProjectBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupProjectBindingSpec) DeepCopyInto(out *GroupProjectBindingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupProjectBindingSpec.
func (in *GroupProjectBindingSpec) DeepCopy() *GroupProjectBindingSpec {
	if in == nil {
		return nil
	}
	out := new(GroupProjectBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HetznerPreset) DeepCopyInto(out *HetznerPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HetznerPreset.
func (in *HetznerPreset) DeepCopy() *HetznerPreset {
	if in == nil {
		return nil
	}
	out := new(HetznerPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAMAllocation) DeepCopyInto(out *IPAMAllocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.IPAMAllocation.DeepCopyInto(&out.IPAMAllocation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAMAllocation.
func (in *IPAMAllocation) DeepCopy() *IPAMAllocation {
	if in == nil {
		return nil
	}
	out := new(IPAMAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPAMAllocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAMAllocationList) DeepCopyInto(out *IPAMAllocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPAMAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAMAllocationList.
func (in *IPAMAllocationList) DeepCopy() *IPAMAllocationList {
	if in == nil {
		return nil
	}
	out := new(IPAMAllocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPAMAllocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAMPool) DeepCopyInto(out *IPAMPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.IPAMPool.DeepCopyInto(&out.IPAMPool)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAMPool.
func (in *IPAMPool) DeepCopy() *IPAMPool {
	if in == nil {
		return nil
	}
	out := new(IPAMPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPAMPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAMPoolList) DeepCopyInto(out *IPAMPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPAMPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAMPoolList.
func (in *IPAMPoolList) DeepCopy() *IPAMPoolList {
	if in == nil {
		return nil
	}
	out := new(IPAMPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPAMPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Incompatibility) DeepCopyInto(out *Incompatibility) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Incompatibility.
func (in *Incompatibility) DeepCopy() *Incompatibility {
	if in == nil {
		return nil
	}
	out := new(Incompatibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeVirtPreset) DeepCopyInto(out *KubeVirtPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeVirtPreset.
func (in *KubeVirtPreset) DeepCopy() *KubeVirtPreset {
	if in == nil {
		return nil
	}
	out := new(KubeVirtPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticAPIConfiguration) DeepCopyInto(out *KubermaticAPIConfiguration) {
	*out = *in
	if in.AccessibleAddons != nil {
		in, out := &in.AccessibleAddons, &out.AccessibleAddons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PProfEndpoint != nil {
		in, out := &in.PProfEndpoint, &out.PProfEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticAPIConfiguration.
func (in *KubermaticAPIConfiguration) DeepCopy() *KubermaticAPIConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticAPIConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticAddonsConfiguration) DeepCopyInto(out *KubermaticAddonsConfiguration) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticAddonsConfiguration.
func (in *KubermaticAddonsConfiguration) DeepCopy() *KubermaticAddonsConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticAddonsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticAuthConfiguration) DeepCopyInto(out *KubermaticAuthConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticAuthConfiguration.
func (in *KubermaticAuthConfiguration) DeepCopy() *KubermaticAuthConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticAuthConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticConfiguration) DeepCopyInto(out *KubermaticConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticConfiguration.
func (in *KubermaticConfiguration) DeepCopy() *KubermaticConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubermaticConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticConfigurationList) DeepCopyInto(out *KubermaticConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubermaticConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticConfigurationList.
func (in *KubermaticConfigurationList) DeepCopy() *KubermaticConfigurationList {
	if in == nil {
		return nil
	}
	out := new(KubermaticConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubermaticConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticConfigurationSpec) DeepCopyInto(out *KubermaticConfigurationSpec) {
	*out = *in
	in.CABundle.DeepCopyInto(&out.CABundle)
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(KubermaticAuthConfiguration)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(KubermaticUIConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(KubermaticAPIConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SeedController != nil {
		in, out := &in.SeedController, &out.SeedController
		*out = new(KubermaticSeedControllerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MasterController != nil {
		in, out := &in.MasterController, &out.MasterController
		*out = new(KubermaticMasterControllerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(KubermaticWebhookConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.UserCluster != nil {
		in, out := &in.UserCluster, &out.UserCluster
		*out = new(KubermaticUserClusterConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Versions.DeepCopyInto(&out.Versions)
	if in.VerticalPodAutoscaler != nil {
		in, out := &in.VerticalPodAutoscaler, &out.VerticalPodAutoscaler
		*out = new(KubermaticVPAConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KubermaticProxyConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticConfigurationSpec.
func (in *KubermaticConfigurationSpec) DeepCopy() *KubermaticConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(KubermaticConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticConfigurationStatus) DeepCopyInto(out *KubermaticConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticConfigurationStatus.
func (in *KubermaticConfigurationStatus) DeepCopy() *KubermaticConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(KubermaticConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticIngressConfiguration) DeepCopyInto(out *KubermaticIngressConfiguration) {
	*out = *in
	if in.CertificateIssuer != nil {
		in, out := &in.CertificateIssuer, &out.CertificateIssuer
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticIngressConfiguration.
func (in *KubermaticIngressConfiguration) DeepCopy() *KubermaticIngressConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticIngressConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticMasterControllerConfiguration) DeepCopyInto(out *KubermaticMasterControllerConfiguration) {
	*out = *in
	if in.ProjectsMigrator != nil {
		in, out := &in.ProjectsMigrator, &out.ProjectsMigrator
		*out = new(KubermaticProjectsMigratorConfiguration)
		**out = **in
	}
	if in.PProfEndpoint != nil {
		in, out := &in.PProfEndpoint, &out.PProfEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticMasterControllerConfiguration.
func (in *KubermaticMasterControllerConfiguration) DeepCopy() *KubermaticMasterControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticMasterControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticProjectsMigratorConfiguration) DeepCopyInto(out *KubermaticProjectsMigratorConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticProjectsMigratorConfiguration.
func (in *KubermaticProjectsMigratorConfiguration) DeepCopy() *KubermaticProjectsMigratorConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticProjectsMigratorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticProxyConfiguration) DeepCopyInto(out *KubermaticProxyConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticProxyConfiguration.
func (in *KubermaticProxyConfiguration) DeepCopy() *KubermaticProxyConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticProxyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticSeedControllerConfiguration) DeepCopyInto(out *KubermaticSeedControllerConfiguration) {
	*out = *in
	if in.PProfEndpoint != nil {
		in, out := &in.PProfEndpoint, &out.PProfEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticSeedControllerConfiguration.
func (in *KubermaticSeedControllerConfiguration) DeepCopy() *KubermaticSeedControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticSeedControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticUIConfiguration) DeepCopyInto(out *KubermaticUIConfiguration) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticUIConfiguration.
func (in *KubermaticUIConfiguration) DeepCopy() *KubermaticUIConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticUIConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticUserClusterConfiguration) DeepCopyInto(out *KubermaticUserClusterConfiguration) {
	*out = *in
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(KubermaticAddonsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SystemApplications != nil {
		in, out := &in.SystemApplications, &out.SystemApplications
		*out = new(SystemApplicationsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(KubermaticUserClusterMonitoringConfiguration)
		**out = **in
	}
	if in.APIServerReplicas != nil {
		in, out := &in.APIServerReplicas, &out.APIServerReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MachineController != nil {
		in, out := &in.MachineController, &out.MachineController
		*out = new(MachineControllerConfiguration)
		**out = **in
	}
	if in.OperatingSystemManager != nil {
		in, out := &in.OperatingSystemManager, &out.OperatingSystemManager
		*out = new(OperatingSystemManager)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticUserClusterConfiguration.
func (in *KubermaticUserClusterConfiguration) DeepCopy() *KubermaticUserClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticUserClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticUserClusterMonitoringConfiguration) DeepCopyInto(out *KubermaticUserClusterMonitoringConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticUserClusterMonitoringConfiguration.
func (in *KubermaticUserClusterMonitoringConfiguration) DeepCopy() *KubermaticUserClusterMonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticUserClusterMonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticVPAComponent) DeepCopyInto(out *KubermaticVPAComponent) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticVPAComponent.
func (in *KubermaticVPAComponent) DeepCopy() *KubermaticVPAComponent {
	if in == nil {
		return nil
	}
	out := new(KubermaticVPAComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticVPAConfiguration) DeepCopyInto(out *KubermaticVPAConfiguration) {
	*out = *in
	if in.Recommender != nil {
		in, out := &in.Recommender, &out.Recommender
		*out = new(KubermaticVPAComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Updater != nil {
		in, out := &in.Updater, &out.Updater
		*out = new(KubermaticVPAComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.AdmissionController != nil {
		in, out := &in.AdmissionController, &out.AdmissionController
		*out = new(KubermaticVPAComponent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticVPAConfiguration.
func (in *KubermaticVPAConfiguration) DeepCopy() *KubermaticVPAConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticVPAConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticVersioningConfiguration) DeepCopyInto(out *KubermaticVersioningConfiguration) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]semver.Semver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Updates != nil {
		in, out := &in.Updates, &out.Updates
		*out = make([]Update, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProviderIncompatibilities != nil {
		in, out := &in.ProviderIncompatibilities, &out.ProviderIncompatibilities
		*out = make([]Incompatibility, len(*in))
		copy(*out, *in)
	}
	if in.ExternalClusters != nil {
		in, out := &in.ExternalClusters, &out.ExternalClusters
		*out = make(map[kubermaticv1.ExternalClusterProvider]ExternalClusterProviderVersioningConfiguration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticVersioningConfiguration.
func (in *KubermaticVersioningConfiguration) DeepCopy() *KubermaticVersioningConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticVersioningConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubermaticWebhookConfiguration) DeepCopyInto(out *KubermaticWebhookConfiguration) {
	*out = *in
	if in.PProfEndpoint != nil {
		in, out := &in.PProfEndpoint, &out.PProfEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubermaticWebhookConfiguration.
func (in *KubermaticWebhookConfiguration) DeepCopy() *KubermaticWebhookConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubermaticWebhookConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLAClusterConfiguration) DeepCopyInto(out *MLAClusterConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.MLAClusterConfiguration.DeepCopyInto(&out.MLAClusterConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLAClusterConfiguration.
func (in *MLAClusterConfiguration) DeepCopy() *MLAClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(MLAClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MLAClusterConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLAClusterConfigurationList) DeepCopyInto(out *MLAClusterConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MLAClusterConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLAClusterConfigurationList.
func (in *MLAClusterConfigurationList) DeepCopy() *MLAClusterConfigurationList {
	if in == nil {
		return nil
	}
	out := new(MLAClusterConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MLAClusterConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLARuleGroup) DeepCopyInto(out *MLARuleGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.MLARuleGroup.DeepCopyInto(&out.MLARuleGroup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLARuleGroup.
func (in *MLARuleGroup) DeepCopy() *MLARuleGroup {
	if in == nil {
		return nil
	}
	out := new(MLARuleGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MLARuleGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLARuleGroupList) DeepCopyInto(out *MLARuleGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MLARuleGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLARuleGroupList.
func (in *MLARuleGroupList) DeepCopy() *MLARuleGroupList {
	if in == nil {
		return nil
	}
	out := new(MLARuleGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MLARuleGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineControllerConfiguration) DeepCopyInto(out *MachineControllerConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineControllerConfiguration.
func (in *MachineControllerConfiguration) DeepCopy() *MachineControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(MachineControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineFlavorFilter) DeepCopyInto(out *MachineFlavorFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineFlavorFilter.
func (in *MachineFlavorFilter) DeepCopy() *MachineFlavorFilter {
	if in == nil {
		return nil
	}
	out := new(MachineFlavorFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRanges) DeepCopyInto(out *NetworkRanges) {
	*out = *in
	if in.CIDRBlocks != nil {
		in, out := &in.CIDRBlocks, &out.CIDRBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRanges.
func (in *NetworkRanges) DeepCopy() *NetworkRanges {
	if in == nil {
		return nil
	}
	out := new(NetworkRanges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixPreset) DeepCopyInto(out *NutanixPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
	if in.CSIPort != nil {
		in, out := &in.CSIPort, &out.CSIPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixPreset.
func (in *NutanixPreset) DeepCopy() *NutanixPreset {
	if in == nil {
		return nil
	}
	out := new(NutanixPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackPreset) DeepCopyInto(out *OpenStackPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackPreset.
func (in *OpenStackPreset) DeepCopy() *OpenStackPreset {
	if in == nil {
		return nil
	}
	out := new(OpenStackPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatingSystemManager) DeepCopyInto(out *OperatingSystemManager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatingSystemManager.
func (in *OperatingSystemManager) DeepCopy() *OperatingSystemManager {
	if in == nil {
		return nil
	}
	out := new(OperatingSystemManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacketPreset) DeepCopyInto(out *PacketPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacketPreset.
func (in *PacketPreset) DeepCopy() *PacketPreset {
	if in == nil {
		return nil
	}
	out := new(PacketPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Preset) DeepCopyInto(out *Preset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Preset.
func (in *Preset) DeepCopy() *Preset {
	if in == nil {
		return nil
	}
	out := new(Preset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Preset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetList) DeepCopyInto(out *PresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Preset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetList.
func (in *PresetList) DeepCopy() *PresetList {
	if in == nil {
		return nil
	}
	out := new(PresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetSpec) DeepCopyInto(out *PresetSpec) {
	*out = *in
	if in.Digitalocean != nil {
		in, out := &in.Digitalocean, &out.Digitalocean
		*out = new(DigitaloceanPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.Hetzner != nil {
		in, out := &in.Hetzner, &out.Hetzner
		*out = new(HetznerPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzurePreset)
		(*in).DeepCopyInto(*out)
	}
	if in.VSphere != nil {
		in, out := &in.VSphere, &out.VSphere
		*out = new(VSpherePreset)
		(*in).DeepCopyInto(*out)
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenStack != nil {
		in, out := &in.OpenStack, &out.OpenStack
		*out = new(OpenStackPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.Packet != nil {
		in, out := &in.Packet, &out.Packet
		*out = new(PacketPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeVirt != nil {
		in, out := &in.KubeVirt, &out.KubeVirt
		*out = new(KubeVirtPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.Alibaba != nil {
		in, out := &in.Alibaba, &out.Alibaba
		*out = new(AlibabaPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.Anexia != nil {
		in, out := &in.Anexia, &out.Anexia
		*out = new(AnexiaPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.Nutanix != nil {
		in, out := &in.Nutanix, &out.Nutanix
		*out = new(NutanixPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.VMwareCloudDirector != nil {
		in, out := &in.VMwareCloudDirector, &out.VMwareCloudDirector
		*out = new(VMwareCloudDirectorPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.GKE != nil {
		in, out := &in.GKE, &out.GKE
		*out = new(GKEPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.EKS != nil {
		in, out := &in.EKS, &out.EKS
		*out = new(EKSPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.AKS != nil {
		in, out := &in.AKS, &out.AKS
		*out = new(AKSPreset)
		(*in).DeepCopyInto(*out)
	}
	if in.Fake != nil {
		in, out := &in.Fake, &out.Fake
		*out = new(FakePreset)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredEmails != nil {
		in, out := &in.RequiredEmails, &out.RequiredEmails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetSpec.
func (in *PresetSpec) DeepCopy() *PresetSpec {
	if in == nil {
		return nil
	}
	out := new(PresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPreset) DeepCopyInto(out *ProviderPreset) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPreset.
func (in *ProviderPreset) DeepCopy() *ProviderPreset {
	if in == nil {
		return nil
	}
	out := new(ProviderPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySettings) DeepCopyInto(out *ProxySettings) {
	*out = *in
	if in.HTTPProxy != nil {
		in, out := &in.HTTPProxy, &out.HTTPProxy
		*out = new(string)
		**out = **in
	}
	if in.NoProxy != nil {
		in, out := &in.NoProxy, &out.NoProxy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySettings.
func (in *ProxySettings) DeepCopy() *ProxySettings {
	if in == nil {
		return nil
	}
	out := new(ProxySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceDetails) DeepCopyInto(out *ResourceDetails) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceDetails.
func (in *ResourceDetails) DeepCopy() *ResourceDetails {
	if in == nil {
		return nil
	}
	out := new(ResourceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuota) DeepCopyInto(out *ResourceQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ResourceQuota.DeepCopyInto(&out.ResourceQuota)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuota.
func (in *ResourceQuota) DeepCopy() *ResourceQuota {
	if in == nil {
		return nil
	}
	out := new(ResourceQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaList) DeepCopyInto(out *ResourceQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaList.
func (in *ResourceQuotaList) DeepCopy() *ResourceQuotaList {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyBinding) DeepCopyInto(out *SSHKeyBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.SSHKeyBinding.DeepCopyInto(&out.SSHKeyBinding)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyBinding.
func (in *SSHKeyBinding) DeepCopy() *SSHKeyBinding {
	if in == nil {
		return nil
	}
	out := new(SSHKeyBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHKeyBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyBindingList) DeepCopyInto(out *SSHKeyBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SSHKeyBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyBindingList.
func (in *SSHKeyBindingList) DeepCopy() *SSHKeyBindingList {
	if in == nil {
		return nil
	}
	out := new(SSHKeyBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHKeyBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretboxEncryptionConfiguration) DeepCopyInto(out *SecretboxEncryptionConfiguration) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]SecretboxKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretboxEncryptionConfiguration.
func (in *SecretboxEncryptionConfiguration) DeepCopy() *SecretboxEncryptionConfiguration {
	if in == nil {
		return nil
	}
	out := new(SecretboxEncryptionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretboxKey) DeepCopyInto(out *SecretboxKey) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretboxKey.
func (in *SecretboxKey) DeepCopy() *SecretboxKey {
	if in == nil {
		return nil
	}
	out := new(SecretboxKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Seed) DeepCopyInto(out *Seed) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Seed.
func (in *Seed) DeepCopy() *Seed {
	if in == nil {
		return nil
	}
	out := new(Seed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Seed) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedCondition) DeepCopyInto(out *SeedCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedCondition.
func (in *SeedCondition) DeepCopy() *SeedCondition {
	if in == nil {
		return nil
	}
	out := new(SeedCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedList) DeepCopyInto(out *SeedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Seed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedList.
func (in *SeedList) DeepCopy() *SeedList {
	if in == nil {
		return nil
	}
	out := new(SeedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedSpec) DeepCopyInto(out *SeedSpec) {
	*out = *in
	if in.Datacenters != nil {
		in, out := &in.Datacenters, &out.Datacenters
		*out = make(map[string]kubermaticv1.DatacenterSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedSpec.
func (in *SeedSpec) DeepCopy() *SeedSpec {
	if in == nil {
		return nil
	}
	out := new(SeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedStatus) DeepCopyInto(out *SeedStatus) {
	*out = *in
	out.Versions = in.Versions
	if in.Datacenters != nil {
		in, out := &in.Datacenters, &out.Datacenters
		*out = make(map[string]kubermaticv1.DatacenterStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(map[SeedConditionType]SeedCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedStatus.
func (in *SeedStatus) DeepCopy() *SeedStatus {
	if in == nil {
		return nil
	}
	out := new(SeedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedVersionsStatus) DeepCopyInto(out *SeedVersionsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedVersionsStatus.
func (in *SeedVersionsStatus) DeepCopy() *SeedVersionsStatus {
	if in == nil {
		return nil
	}
	out := new(SeedVersionsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemApplicationsConfiguration) DeepCopyInto(out *SystemApplicationsConfiguration) {
	*out = *in
	if in.HelmRegistryConfigFile != nil {
		in, out := &in.HelmRegistryConfigFile, &out.HelmRegistryConfigFile
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemApplicationsConfiguration.
func (in *SystemApplicationsConfiguration) DeepCopy() *SystemApplicationsConfiguration {
	if in == nil {
		return nil
	}
	out := new(SystemApplicationsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Update) DeepCopyInto(out *Update) {
	*out = *in
	if in.Automatic != nil {
		in, out := &in.Automatic, &out.Automatic
		*out = new(bool)
		**out = **in
	}
	if in.AutomaticNodeUpdate != nil {
		in, out := &in.AutomaticNodeUpdate, &out.AutomaticNodeUpdate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Update.
func (in *Update) DeepCopy() *Update {
	if in == nil {
		return nil
	}
	out := new(Update)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.User.DeepCopyInto(&out.User)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *User) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserList) DeepCopyInto(out *UserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserList.
func (in *UserList) DeepCopy() *UserList {
	if in == nil {
		return nil
	}
	out := new(UserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserProjectBinding) DeepCopyInto(out *UserProjectBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserProjectBinding.
func (in *UserProjectBinding) DeepCopy() *UserProjectBinding {
	if in == nil {
		return nil
	}
	out := new(UserProjectBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserProjectBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserProjectBindingList) DeepCopyInto(out *UserProjectBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserProjectBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserProjectBindingList.
func (in *UserProjectBindingList) DeepCopy() *UserProjectBindingList {
	if in == nil {
		return nil
	}
	out := new(UserProjectBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserProjectBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserProjectBindingSpec) DeepCopyInto(out *UserProjectBindingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserProjectBindingSpec.
func (in *UserProjectBindingSpec) DeepCopy() *UserProjectBindingSpec {
	if in == nil {
		return nil
	}
	out := new(UserProjectBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSSHKey) DeepCopyInto(out *UserSSHKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.UserSSHKey.DeepCopyInto(&out.UserSSHKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSSHKey.
func (in *UserSSHKey) DeepCopy() *UserSSHKey {
	if in == nil {
		return nil
	}
	out := new(UserSSHKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserSSHKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSSHKeyList) DeepCopyInto(out *UserSSHKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserSSHKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSSHKeyList.
func (in *UserSSHKeyList) DeepCopy() *UserSSHKeyList {
	if in == nil {
		return nil
	}
	out := new(UserSSHKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserSSHKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareCloudDirectorPreset) DeepCopyInto(out *VMwareCloudDirectorPreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareCloudDirectorPreset.
func (in *VMwareCloudDirectorPreset) DeepCopy() *VMwareCloudDirectorPreset {
	if in == nil {
		return nil
	}
	out := new(VMwareCloudDirectorPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSpherePreset) DeepCopyInto(out *VSpherePreset) {
	*out = *in
	in.ProviderPreset.DeepCopyInto(&out.ProviderPreset)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSpherePreset.
func (in *VSpherePreset) DeepCopy() *VSpherePreset {
	if in == nil {
		return nil
	}
	out := new(VSpherePreset)
	in.DeepCopyInto(out)
	return out
}
