//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright  The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"encoding/json"
	kubermaticv1 "k8c.io/api/v3/pkg/apis/kubermatic/v1"
	open_policy_agent "k8c.io/api/v3/pkg/apis/open-policy-agent"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRegistry) DeepCopyInto(out *AllowedRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRegistry.
func (in *AllowedRegistry) DeepCopy() *AllowedRegistry {
	if in == nil {
		return nil
	}
	out := new(AllowedRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AllowedRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRegistryList) DeepCopyInto(out *AllowedRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AllowedRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRegistryList.
func (in *AllowedRegistryList) DeepCopy() *AllowedRegistryList {
	if in == nil {
		return nil
	}
	out := new(AllowedRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AllowedRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRegistrySpec) DeepCopyInto(out *AllowedRegistrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRegistrySpec.
func (in *AllowedRegistrySpec) DeepCopy() *AllowedRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(AllowedRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	in.ScheduledTime.DeepCopyInto(&out.ScheduledTime)
	in.BackupStartTime.DeepCopyInto(&out.BackupStartTime)
	in.BackupFinishedTime.DeepCopyInto(&out.BackupFinishedTime)
	in.DeleteStartTime.DeepCopyInto(&out.DeleteStartTime)
	in.DeleteFinishedTime.DeepCopyInto(&out.DeleteFinishedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Constraint) DeepCopyInto(out *Constraint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Constraint.
func (in *Constraint) DeepCopy() *Constraint {
	if in == nil {
		return nil
	}
	out := new(Constraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Constraint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintList) DeepCopyInto(out *ConstraintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Constraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintList.
func (in *ConstraintList) DeepCopy() *ConstraintList {
	if in == nil {
		return nil
	}
	out := new(ConstraintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintMatch) DeepCopyInto(out *ConstraintMatch) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]ConstraintMatchKind, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedNamespaces != nil {
		in, out := &in.ExcludedNamespaces, &out.ExcludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintMatch.
func (in *ConstraintMatch) DeepCopy() *ConstraintMatch {
	if in == nil {
		return nil
	}
	out := new(ConstraintMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintMatchKind) DeepCopyInto(out *ConstraintMatchKind) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintMatchKind.
func (in *ConstraintMatchKind) DeepCopy() *ConstraintMatchKind {
	if in == nil {
		return nil
	}
	out := new(ConstraintMatchKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ConstraintParameters) DeepCopyInto(out *ConstraintParameters) {
	{
		in := &in
		*out = make(ConstraintParameters, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintParameters.
func (in ConstraintParameters) DeepCopy() ConstraintParameters {
	if in == nil {
		return nil
	}
	out := new(ConstraintParameters)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintSelector) DeepCopyInto(out *ConstraintSelector) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]kubermaticv1.CloudProvider, len(*in))
		copy(*out, *in)
	}
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintSelector.
func (in *ConstraintSelector) DeepCopy() *ConstraintSelector {
	if in == nil {
		return nil
	}
	out := new(ConstraintSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintSpec) DeepCopyInto(out *ConstraintSpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(ConstraintParameters, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ConstraintSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintSpec.
func (in *ConstraintSpec) DeepCopy() *ConstraintSpec {
	if in == nil {
		return nil
	}
	out := new(ConstraintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplate) DeepCopyInto(out *ConstraintTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplate.
func (in *ConstraintTemplate) DeepCopy() *ConstraintTemplate {
	if in == nil {
		return nil
	}
	out := new(ConstraintTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplateList) DeepCopyInto(out *ConstraintTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConstraintTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplateList.
func (in *ConstraintTemplateList) DeepCopy() *ConstraintTemplateList {
	if in == nil {
		return nil
	}
	out := new(ConstraintTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplateSelector) DeepCopyInto(out *ConstraintTemplateSelector) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]kubermaticv1.CloudProvider, len(*in))
		copy(*out, *in)
	}
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplateSelector.
func (in *ConstraintTemplateSelector) DeepCopy() *ConstraintTemplateSelector {
	if in == nil {
		return nil
	}
	out := new(ConstraintTemplateSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplateSpec) DeepCopyInto(out *ConstraintTemplateSpec) {
	*out = *in
	in.CRD.DeepCopyInto(&out.CRD)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]open_policy_agent.Target, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplateSpec.
func (in *ConstraintTemplateSpec) DeepCopy() *ConstraintTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ConstraintTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdBackupConfig) DeepCopyInto(out *EtcdBackupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdBackupConfig.
func (in *EtcdBackupConfig) DeepCopy() *EtcdBackupConfig {
	if in == nil {
		return nil
	}
	out := new(EtcdBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdBackupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdBackupConfigCondition) DeepCopyInto(out *EtcdBackupConfigCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdBackupConfigCondition.
func (in *EtcdBackupConfigCondition) DeepCopy() *EtcdBackupConfigCondition {
	if in == nil {
		return nil
	}
	out := new(EtcdBackupConfigCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdBackupConfigList) DeepCopyInto(out *EtcdBackupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EtcdBackupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdBackupConfigList.
func (in *EtcdBackupConfigList) DeepCopy() *EtcdBackupConfigList {
	if in == nil {
		return nil
	}
	out := new(EtcdBackupConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdBackupConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdBackupConfigSpec) DeepCopyInto(out *EtcdBackupConfigSpec) {
	*out = *in
	out.Cluster = in.Cluster
	if in.Keep != nil {
		in, out := &in.Keep, &out.Keep
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdBackupConfigSpec.
func (in *EtcdBackupConfigSpec) DeepCopy() *EtcdBackupConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EtcdBackupConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdBackupConfigStatus) DeepCopyInto(out *EtcdBackupConfigStatus) {
	*out = *in
	if in.CurrentBackups != nil {
		in, out := &in.CurrentBackups, &out.CurrentBackups
		*out = make([]BackupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(map[EtcdBackupConfigConditionType]EtcdBackupConfigCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdBackupConfigStatus.
func (in *EtcdBackupConfigStatus) DeepCopy() *EtcdBackupConfigStatus {
	if in == nil {
		return nil
	}
	out := new(EtcdBackupConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdRestore) DeepCopyInto(out *EtcdRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdRestore.
func (in *EtcdRestore) DeepCopy() *EtcdRestore {
	if in == nil {
		return nil
	}
	out := new(EtcdRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdRestoreList) DeepCopyInto(out *EtcdRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EtcdRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdRestoreList.
func (in *EtcdRestoreList) DeepCopy() *EtcdRestoreList {
	if in == nil {
		return nil
	}
	out := new(EtcdRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdRestoreSpec) DeepCopyInto(out *EtcdRestoreSpec) {
	*out = *in
	out.Cluster = in.Cluster
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdRestoreSpec.
func (in *EtcdRestoreSpec) DeepCopy() *EtcdRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(EtcdRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdRestoreStatus) DeepCopyInto(out *EtcdRestoreStatus) {
	*out = *in
	in.RestoreTime.DeepCopyInto(&out.RestoreTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdRestoreStatus.
func (in *EtcdRestoreStatus) DeepCopy() *EtcdRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(EtcdRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalCluster) DeepCopyInto(out *ExternalCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalCluster.
func (in *ExternalCluster) DeepCopy() *ExternalCluster {
	if in == nil {
		return nil
	}
	out := new(ExternalCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterAKSCloudSpec) DeepCopyInto(out *ExternalClusterAKSCloudSpec) {
	*out = *in
	if in.CredentialsReference != nil {
		in, out := &in.CredentialsReference, &out.CredentialsReference
		*out = new(kubermaticv1.GlobalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterAKSCloudSpec.
func (in *ExternalClusterAKSCloudSpec) DeepCopy() *ExternalClusterAKSCloudSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterAKSCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterBringYourOwnCloudSpec) DeepCopyInto(out *ExternalClusterBringYourOwnCloudSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterBringYourOwnCloudSpec.
func (in *ExternalClusterBringYourOwnCloudSpec) DeepCopy() *ExternalClusterBringYourOwnCloudSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterBringYourOwnCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterCloudSpec) DeepCopyInto(out *ExternalClusterCloudSpec) {
	*out = *in
	if in.GKE != nil {
		in, out := &in.GKE, &out.GKE
		*out = new(ExternalClusterGKECloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EKS != nil {
		in, out := &in.EKS, &out.EKS
		*out = new(ExternalClusterEKSCloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AKS != nil {
		in, out := &in.AKS, &out.AKS
		*out = new(ExternalClusterAKSCloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeOne != nil {
		in, out := &in.KubeOne, &out.KubeOne
		*out = new(ExternalClusterKubeOneCloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BringYourOwn != nil {
		in, out := &in.BringYourOwn, &out.BringYourOwn
		*out = new(ExternalClusterBringYourOwnCloudSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterCloudSpec.
func (in *ExternalClusterCloudSpec) DeepCopy() *ExternalClusterCloudSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterCondition) DeepCopyInto(out *ExternalClusterCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterCondition.
func (in *ExternalClusterCondition) DeepCopy() *ExternalClusterCondition {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterEKSCloudSpec) DeepCopyInto(out *ExternalClusterEKSCloudSpec) {
	*out = *in
	if in.CredentialsReference != nil {
		in, out := &in.CredentialsReference, &out.CredentialsReference
		*out = new(kubermaticv1.GlobalSecretKeySelector)
		**out = **in
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterEKSCloudSpec.
func (in *ExternalClusterEKSCloudSpec) DeepCopy() *ExternalClusterEKSCloudSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterEKSCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterGKECloudSpec) DeepCopyInto(out *ExternalClusterGKECloudSpec) {
	*out = *in
	if in.CredentialsReference != nil {
		in, out := &in.CredentialsReference, &out.CredentialsReference
		*out = new(kubermaticv1.GlobalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterGKECloudSpec.
func (in *ExternalClusterGKECloudSpec) DeepCopy() *ExternalClusterGKECloudSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterGKECloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterKubeOneCloudSpec) DeepCopyInto(out *ExternalClusterKubeOneCloudSpec) {
	*out = *in
	if in.CredentialsReference != nil {
		in, out := &in.CredentialsReference, &out.CredentialsReference
		*out = new(kubermaticv1.GlobalSecretKeySelector)
		**out = **in
	}
	if in.SSHReference != nil {
		in, out := &in.SSHReference, &out.SSHReference
		*out = new(kubermaticv1.GlobalSecretKeySelector)
		**out = **in
	}
	if in.ManifestReference != nil {
		in, out := &in.ManifestReference, &out.ManifestReference
		*out = new(kubermaticv1.GlobalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterKubeOneCloudSpec.
func (in *ExternalClusterKubeOneCloudSpec) DeepCopy() *ExternalClusterKubeOneCloudSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterKubeOneCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterList) DeepCopyInto(out *ExternalClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterList.
func (in *ExternalClusterList) DeepCopy() *ExternalClusterList {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterNetworkRanges) DeepCopyInto(out *ExternalClusterNetworkRanges) {
	*out = *in
	if in.CIDRBlocks != nil {
		in, out := &in.CIDRBlocks, &out.CIDRBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterNetworkRanges.
func (in *ExternalClusterNetworkRanges) DeepCopy() *ExternalClusterNetworkRanges {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterNetworkRanges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterNetworkingConfig) DeepCopyInto(out *ExternalClusterNetworkingConfig) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(ExternalClusterNetworkRanges)
		(*in).DeepCopyInto(*out)
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(ExternalClusterNetworkRanges)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterNetworkingConfig.
func (in *ExternalClusterNetworkingConfig) DeepCopy() *ExternalClusterNetworkingConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterNetworkingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterSpec) DeepCopyInto(out *ExternalClusterSpec) {
	*out = *in
	if in.KubeconfigReference != nil {
		in, out := &in.KubeconfigReference, &out.KubeconfigReference
		*out = new(kubermaticv1.GlobalSecretKeySelector)
		**out = **in
	}
	out.Version = in.Version.DeepCopy()
	in.CloudSpec.DeepCopyInto(&out.CloudSpec)
	if in.ClusterNetwork != nil {
		in, out := &in.ClusterNetwork, &out.ClusterNetwork
		*out = new(ExternalClusterNetworkingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterSpec.
func (in *ExternalClusterSpec) DeepCopy() *ExternalClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterStatus) DeepCopyInto(out *ExternalClusterStatus) {
	*out = *in
	out.Condition = in.Condition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterStatus.
func (in *ExternalClusterStatus) DeepCopy() *ExternalClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuota) DeepCopyInto(out *ResourceQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuota.
func (in *ResourceQuota) DeepCopy() *ResourceQuota {
	if in == nil {
		return nil
	}
	out := new(ResourceQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaList) DeepCopyInto(out *ResourceQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaList.
func (in *ResourceQuotaList) DeepCopy() *ResourceQuotaList {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaSpec) DeepCopyInto(out *ResourceQuotaSpec) {
	*out = *in
	out.Subject = in.Subject
	in.Quota.DeepCopyInto(&out.Quota)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaSpec.
func (in *ResourceQuotaSpec) DeepCopy() *ResourceQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaStatus) DeepCopyInto(out *ResourceQuotaStatus) {
	*out = *in
	if in.GlobalUsage != nil {
		in, out := &in.GlobalUsage, &out.GlobalUsage
		*out = new(kubermaticv1.ResourceDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalUsage != nil {
		in, out := &in.LocalUsage, &out.LocalUsage
		*out = new(kubermaticv1.ResourceDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaStatus.
func (in *ResourceQuotaStatus) DeepCopy() *ResourceQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaSubject) DeepCopyInto(out *ResourceQuotaSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaSubject.
func (in *ResourceQuotaSubject) DeepCopy() *ResourceQuotaSubject {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaSubject)
	in.DeepCopyInto(out)
	return out
}
