//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright  The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package machinecontroller

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigVarBool) DeepCopyInto(out *ConfigVarBool) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(bool)
		**out = **in
	}
	out.SecretKeyRef = in.SecretKeyRef
	out.ConfigMapKeyRef = in.ConfigMapKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigVarBool.
func (in *ConfigVarBool) DeepCopy() *ConfigVarBool {
	if in == nil {
		return nil
	}
	out := new(ConfigVarBool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigVarString) DeepCopyInto(out *ConfigVarString) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
	out.ConfigMapKeyRef = in.ConfigMapKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigVarString.
func (in *ConfigVarString) DeepCopy() *ConfigVarString {
	if in == nil {
		return nil
	}
	out := new(ConfigVarString)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfigMapKeySelector) DeepCopyInto(out *GlobalConfigMapKeySelector) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfigMapKeySelector.
func (in *GlobalConfigMapKeySelector) DeepCopy() *GlobalConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(GlobalConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalObjectKeySelector) DeepCopyInto(out *GlobalObjectKeySelector) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalObjectKeySelector.
func (in *GlobalObjectKeySelector) DeepCopy() *GlobalObjectKeySelector {
	if in == nil {
		return nil
	}
	out := new(GlobalObjectKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSecretKeySelector) DeepCopyInto(out *GlobalSecretKeySelector) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSecretKeySelector.
func (in *GlobalSecretKeySelector) DeepCopy() *GlobalSecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(GlobalSecretKeySelector)
	in.DeepCopyInto(out)
	return out
}
